#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_UPDATE_ART_DIALOG                   106
#define IDD_DIALOG_CONF                         108
#define IDD_DIALOG_FIND_RELEASE                 109
#define IDD_DIALOG_UPDATE_TAGS                  110
#define IDD_DIALOG_CONF_TAGGING                 111
#define IDD_DIALOG_CONF_ART                     113
#define IDD_DIALOG_CONF_OAUTH                   114
#define IDD_DIALOG_TAG_MAPPINGS                 116
#define IDD_DIALOG_CONF_FIND_RELEASE_DIALOG     122
#define IDD_DIALOG_PREVIEW_TAGS                 125
#define IDD_DIALOG_CONF_MATCHING_DIALOG         127
#define IDD_DIALOG_MATCH_TRACKS                 128
#define IDD_DIALOG_PROMPT                       130
#define IDD_DIALOG_CONF_CACHING_DIALOG          133
#define IDC_EDIT_TAG_MAPPINGS_BUTTON            1029
#define IDC_MOVE_UP_BUTTON                      1035
#define IDC_MOVE_DOWN_BUTTON                    1036
#define IDC_REMOVE_FILE_TRACK_BUTTON            1044
#define IDC_REMOVE_DISCOGS_TRACK_BUTTON         1045
#define IDAPPLY                                 1052
#define IDC_SAVE_ALBUM_ART_CHECK                1054
#define IDC_ALBUM_ART_DIR_EDIT                  1062
#define IDC_CONF_DEFAULTS_BUTTON                1064
#define IDC_ARTIST_ART_DIR_EDIT                 1067
#define IDC_ENABLE_ANV_CHECK                    1068
#define IDC_ARTIST_LIST                         1071
#define IDC_SEARCH_TEXT                         1072
#define IDC_SEARCH_BUTTON                       1073
#define IDC_RELEASE_LIST                        1074
#define IDOAUTHTEST                             1075
#define IDC_RELEASE_URL_TEXT                    1076
#define IDC_FILTER_EDIT                         1084
#define IDC_UPD_TAGS_REPLACE_ANV_CHECK          1087
#define IDC_MOVE_THE_AT_BEGINNING_CHECK         1088
#define IDC_ONLY_EXACT_MATCHES_CHECK            1091
#define IDC_TAB                                 1093
#define IDC_SAVE_ARTIST_ART_CHECK               1094
#define IDC_BACK_BUTTON                         1095
#define IDC_UPDATE_ART_ALBUM_CHECK              1104
#define IDC_UPDATE_ART_ARTIST_CHECK             1105
#define IDC_CLEAR_FILTER_BUTTON                 1106
#define IDC_CONFIGURE_BUTTON                    1108
#define IDC_OAUTH_TOKEN_EDIT                    1108
#define IDC_OAUTH_SECRET_EDIT                   1109
#define IDOAUTHGENERATE                         1110
#define IDC_OAUTH_PIN_EDIT                      1111
#define IDOAUTHAUTHORIZE                        1112
#define IDC_ARTIST_ART_OVERWRITE_CHECK          1113
#define IDC_FILE_LIST                           1114
#define IDC_RELEASE_FORMATTING_EDIT             1115
#define IDC_REMOVE_EXCLUDING_TAGS               1116
#define IDC_RESULTS_GROUP                       1117
#define IDC_SYNTAX_HELP                         1118
#define IDC_ARTIST_ART_DIR_LABEL                1119
#define IDC_DISCARD_NUMERIC_SUFFIXES_CHECK      1120
#define IDC_ENABLE_AUTO_SEARCH_CHECK            1121
#define IDC_FAILED_TO_MATCH_TRACKS              1122
#define IDC_LABEL_FILTER                        1123
#define IDC_MATCH_USING_DURATIONS               1124
#define IDC_REMOVE_TAG                          1125
#define IDC_ARTIST_ART_IDS_EDIT                 1126
#define IDC_DISCOGS_TRACK_LIST                  1127
#define IDC_LABEL_RELEASE_ID                    1128
#define IDC_MATCH_USING_NUMBERS                 1129
#define IDC_TAG_LIST                            1130
#define IDC_ADD_TAG                             1131
#define IDC_ARTIST_ART_IDS_LABEL                1132
#define IDC_ARTIST_ART_PREFIX_LABEL             1134
#define IDC_SKIP_FIND_RELEASE_DIALOG_CHECK      1134
#define IDC_DEFAULT_TAGS                        1136
#define IDC_LABEL_RELEASES                      1137
#define IDC_MASTER_FORMATTING_EDIT              1138
#define IDC_MATCH_ASSUME_SORTED                 1139
#define IDC_REMOVE_OTHER_TAGS                   1140
#define IDC_ARTIST_ART_FETCH_ALL_CHECK          1141
#define IDC_TAG_MAPPINGS_GROUP                  1143
#define IDC_SKIP_RELEASE_DIALOG_CHECK           1144
#define IDC_TRACKLIST_GROUP                     1145
#define IDC_ALBUM_ART_PREFIX_EDIT               1146
#define IDC_ALBUM_ART_PREFIX_LABEL              1148
#define IDC_MATCHED_TRACKS                      1149
#define IDC_ARTIST_ART_PREFIX_EDIT              1150
#define IDC_ALBUM_ART_OVERWRITE_CHECK           1151
#define IDC_ALBUM_ART_FETCH_ALL_CHECK           1152
#define IDC_ASSUMED_MATCH_TRACKS                1153
#define IDC_DISCOGS_FORMATTING_EDIT             1154
#define IDC_FILE_FORMATTING_EDIT                1155
#define IDC_PREVIEW_LIST                        1156
#define IDC_MASTER_SUB_FORMATTING_EDIT          1157
#define IDC_OPTIONS_GROUP                       1159
#define IDC_PREVIEW_TAGS_BUTTON                 1160
#define IDC_PROMPT_LABEL                        1161
#define IDC_SKIP_PREVIEW_DIALOG                 1162
#define IDC_PROMPT_EDIT                         1163
#define IDC_REPLACE_ANV_CHECK                   1164
#define IDC_ALBUM_ART                           1165
#define IDC_VIEW_NORMAL                         1169
#define IDC_VIEW_DIFFERENCE                     1170
#define IDC_VIEW_ORIGINAL                       1171
#define IDC_VIEW_DEBUG                          1172
#define IDC_VIEW_GROUP                          1173
#define IDC_PREVIEW_ALL_CHANGES                 1174
#define IDC_UPDATE_RADIO                        1175
#define IDC_WRITE_RADIO                         1176
#define IDC_MANUALLY_PROMPT                     1177
#define IDC_WRITE_TAGS_BUTTON                   1178
#define IDC_SKIP_BUTTON                         1179
#define IDC_NEXT_BUTTON                         1180
#define IDC_HIDDEN_AS_REGULAR_CHECK             1181
#define IDC_CLEAR_CACHE_RELEASES                1183
#define IDC_CLEAR_CACHE_MASTERS                 1184
#define IDC_CLEAR_CACHE_ARTISTS                 1185
#define IDC_CLEAR_CACHE_COLLECTION              1186
#define IDC_CACHED_OBJECTS_EDIT                 1187
#define IDC_PROCESS_RELEASE_BUTTON              1188
#define IDC_ALBUM_ART_EMBED                     40000
#define IDC_EXPORT_TAGS                         40000
#define IDC_PREVIOUS_BUTTON                     40000
#define IDC_SKIP_VIDEO_TRACKS                   40000
#define IDC_ALBUM_ART_DIR_LABEL                 40001
#define IDC_IMPORT_TAGS                         40001
#define IDC_ARTIST_ART_EMBED                    40002
